# Generated by Django 4.2 on 2023-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('O', 'Operational'), ('NW', 'Not Working')], default='O', max_length=2)),
                ('direction', models.CharField(choices=[('U', 'Up'), ('D', 'Down'), ('N', 'None')], default='N', max_length=1)),
                ('door', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='C', max_length=1)),
                ('requests', models.JSONField(default=list)),
            ],
        ),
    ]
